# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/expense_tracker
spring.datasource.username=root
spring.datasource.password=root

# Server Port
server.port=8080

# Mistral API
mistral.api.key=U1xUzvLfT02gU4UKCp4trzCIfz9BHUCe

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=yedukondalumogili816@gmail.com
spring.mail.password=cavvpnpsnzcnsxii
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true